name: Android Pull Request & Master CI

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:

  apk:
    name: Generate APK
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Create APIKEY
        run: |
          echo $GITHUB_WORKSPACE
          echo $CLIENT_SECRET
          echo $CLIENT_ID
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      - uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "/home/runner/work/SpotifyMusicParty/SpotifyMusicParty/apikey.properties"
          FILE_DATA: "CLIENT_ID = ${{ secrets.CLIENT_ID }} \nCLIENT_SECRET = ${{ secrets.CLIENT_SECRET }}"
      - name: Create APIKEY
        run: |
          cd /home/runner/work/SpotifyMusicParty/SpotifyMusicParty/
          ls
          cat apikey.properties
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
